# Generated by Django 3.1.2 on 2020-10-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='module_name',
            field=models.CharField(default='simple_questions', max_length=50),
            preserve_default=False,
        ),
    ]
