# Generated by Django 3.1.2 on 2020-10-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='class_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
