# Generated by Django 3.1.2 on 2020-11-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='number_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='number_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
