language: python
python:
  - "3.8"
services:
  - docker

install:
  - pip install pipenv
  - pipenv install

env:
  - DOCKER_COMPOSE_VERSION=3.3

script:
  - docker-compose up -d --build
  - docker-compose run web python manage.py test
  - coverage run manage.py test

after_sucess:
  coveralls
