language: python
python:
  - "3.8"
services:
  - docker
#  - postgresql

#before_script:
#  - psql -c 'create database db;' -U postgres

install:
  - pip install pipenv
  - pipenv install

script:
#  - pipenv run python manage.py test
  - docker-compose run web python manage.py test --env-file /dev/null