language: python
python:
  - "3.8"
services:
  - postgresql

before_script:
  - psql -c 'create database db;' -U postgres

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run python manage.py test