language: python
python:
  - "3.8"
services:
  - docker

install:
  - pip install pipenv
  - pipenv install
  - npm install
  - npm install babel-core@^7.0.0-bridge.0 --save-dev --dev jest --save-dev vue-jest vue-template-compiler --save-dev jest-serializer-vue
  - npm install -g yarn
  - yarn install
  - yarn add @vue/test-utils


env:
  - DOCKER_COMPOSE_VERSION=3.3

script:
  - docker-compose run web python manage.py migrate
  - docker-compose run web python manage.py test
  - docker-compose run web prospector --uses django
  - docker-compose run web yarn jest


after_success:
  - coveralls
