language: python
python:
  - "3.8"
services:
  - docker
#  - postgresql

#before_script:
#  - psql -c 'create database db;' -U postgres

install:
  - pip install pipenv
  - pipenv install

script:
#  - pipenv run python manage.py test
  - curl -L https://github.com/docker/compose/releases/download/1.11.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose run web python manage.py test --env-file /dev/null