version: "3.3"
services:
  web:
    build: .
    command: bash -c "python /code/manage.py collectstatic --noinput &&
                      python /code/manage.py migrate &&
                      gunicorn music_theory_api.wsgi -b 0.0.0.0:8000"
                      
    environment:
      - SECRET_KEY="${SECRET_KEY}"
      - DEBUG="${DEBUG}"
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}


    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: