
version: "3.3"
services:
  db:
    image: postgres:11
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
  migration:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate'
    volumes:
    - .:/usr/src/app
    depends_on:
    - db
  web:
    build: .
    command: bash -c "python /code/manage.py collectstatic --noinput &&
      gunicorn music_theory_api.wsgi -b 0.0.0.0:8000 --worker-tmp-dir /dev/shm --workers 2"

    environment:
    - SECRET_KEY="${SECRET_KEY}"
    - DEBUG="${DEBUG}"
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_NAME=${DATABASE_NAME}


    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
    - db
    - migration

volumes:
  postgres_data: