# Generated by Django 3.1.2 on 2020-10-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('B', 'Base'), ('P', 'Premium')], max_length=1),
        ),
    ]
