# Generated by Django 3.1.2 on 2020-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('B', 'Base'), ('P', 'Premium')], default='B', max_length=1),
        ),
    ]
