# Generated by Django 3.1.2 on 2020-10-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20201015_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_user',
            field=models.BooleanField(default=False),
        ),
    ]
